### ISSUE TITLE
Can not find myself in the list 

### ISSUE THREAD

**Issue by somekindofwallflower** [glaukiol1/top-github-commiters#3]
I actually have more than 42 followers, but I don't understand why I can find myself at Italy top users.

**Comment by glaukiol1** [comment]
Hello, you are #119	in Italy. You can check yourself in the `output/italy.md` file.

**Comment by somekindofwallflower** [comment]
> Hello, you are #119 in Italy. You can check yourself in the `output/italy.md` file.

Why are you displaying name instead of username?

**Comment by glaukiol1** [comment]
Well I coded this over a span of 4 hours, and didn't really think about the design aspects. You can open a PR editing the source code if you would like.
