### ISSUE TITLE
random question lol

### ISSUE THREAD

**Issue by CertifiedRice** [glaukiol1/top-github-commiters#4]
In [USA](https://github.com/glaukiol1/top-github-commiters/blob/main/output/usa,united+states,united+states+of+america,america.md)

Why `159` followers minimum to be on the list?

**Comment by glaukiol1** [comment]
Because of GitHub GraphQLs response. A maximum of 995 users can be fetched. You have to be top 995 in followers to see your stats.

**Comment by CertifiedRice** [comment]
ok
